version: '3.8'

services:
  # --- Service 1: Database MySQL ---
  mysql_db:
    image: mysql:8.0
    container_name: rawattani_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rawattani_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # --- Service 2: Backend Flask ---
  backend:
    build: .  
    container_name: rawattani_flask
    
    # === TAMBAHKAN BARIS INI ===
    restart: always 
    # ===========================
    
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - FLASK_DEBUG=1

volumes:
  mysql_data: